// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Get(arg1:string,arg2:string):Promise<main.Config>;

export function Set(arg1:string,arg2:main.Config):Promise<void>;
